package task3_exception;

public class program1 {

	public void test()
	{

    int a,b,c;
    a=10;b=5;c=0;
    c=a/b;
   
}

}
